### ISSUE TITLE
Simulation doesn't start

### ISSUE THREAD

**Issue by tri03** [ndrs92/DesignSPHysics#20] opened 2017-12-11 09:56 UTC
Hi, I try to use DesignSPHysics on Windows 7 previously for run DualSPHysics I use XML. I try to run test example but it doesn't start running.
![untitled](https://user-images.githubusercontent.com/34439337/33825345-aead6644-dea4-11e7-8a0c-b14663d5d55a.png)

**Comment by tri03** [comment] 2017-12-11 10:01
![untitled2](https://user-images.githubusercontent.com/34439337/33825636-9df06dc8-dea5-11e7-87ad-5866931333ef.png)

**Comment by ndrs92** [comment] 2017-12-11 10:07
Hi there.

This is the first time I see something like it, so I'm going to have to ask you to do something (sorry!).

Can you do this steps for me?

1. Restart FreeCAD
2. Enable the Report View in the FreeCAD top Menu > View > Panels > Report View.
3. Load DesignSPHysics
4. Load the case
5. Save the case with GenCase
6. Run the simulation.

So after this, hopefully, you will have a chunk of red text with errors in the recenlty opened Report View. Can you paste me that output over here?

Thank you so much for the error report.

**Comment by tri03** [comment] 2017-12-12 01:50
I try to save but there is a warning as shown in the picture and it didn't start running.
![untitled](https://user-images.githubusercontent.com/34439337/33863254-2a87c540-df2a-11e7-9684-727eb3174216.png)

**Comment by ndrs92** [comment] 2017-12-12 09:14
Okay, there you have the error. That's definitely not a warning, but a fatal error.

As the error said, **the saving path for the case contains spaces**. It is a known bug already opened as an issue in #18.

I'll try to fix it and include it in the next release.

To temporary fix your error please save the case in something like **C:\cases\your_case** or another disk / usb drive with the same structure. Remember, with no spaces in the path, so **C:\my cases\your_case** wouldn't work.

So, closing this as it is a duplicate of #18

**Closed by ndrs92** 2017-12-12 09:14 UTC
Labels: bug
